I'm sorry, but an uncaught exception occurred.

While running game code:
WindowsError: [Error 32] The process cannot access the file because it is being used by another process: u'C:\\Users\\iange\\AppData\\Roaming/RenPy/BroncoHacks_Dating_Sim-1745018015\\persistent'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Users\iange\Downloads\renpy-7.8.7-sdk/renpy/bootstrap.py", line 359, in bootstrap
    renpy.main.main()
  File "C:\Users\iange\Downloads\renpy-7.8.7-sdk/renpy/main.py", line 666, in main
    renpy.persistent.update(True)
  File "C:\Users\iange\Downloads\renpy-7.8.7-sdk/renpy/persistent.py", line 434, in update
    save()
  File "C:\Users\iange\Downloads\renpy-7.8.7-sdk/renpy/persistent.py", line 456, in save
    renpy.loadsave.location.save_persistent(compressed)
  File "C:\Users\iange\Downloads\renpy-7.8.7-sdk/renpy/savelocation.py", line 622, in save_persistent
    l.save_persistent(data)
  File "C:\Users\iange\Downloads\renpy-7.8.7-sdk/renpy/savelocation.py", line 430, in save_persistent
    safe_rename(fn_new, fn)
  File "C:\Users\iange\Downloads\renpy-7.8.7-sdk/renpy/loadsave.py", line 303, in safe_rename
    os.unlink(new)
WindowsError: [Error 32] The process cannot access the file because it is being used by another process: u'C:\\Users\\iange\\AppData\\Roaming/RenPy/BroncoHacks_Dating_Sim-1745018015\\persistent'

Windows-10-10.0.26100 AMD64
Ren'Py 7.8.7.25031702
BroncoHacks_Dating_Sim 1.0
Fri Apr 18 19:53:46 2025
